version: '3'

services:

  middleman:
    image: docker-middleman
    container_name: dev-middleman
    build: .

    tty: true

    ports:
      - 4567:80

    volumes:
      - "${VOLUME}:/tmp/share"

    command: /bin/bash
    # sh -c "/tmp/middleman.sh"
