source 'https://rubygems.org'

gem 'middleman'
gem 'middleman-autoprefixer'
gem 'middleman-compass'
gem 'middleman-deploy', '2.0.0.pre.alpha'
gem 'middleman-livereload'
gem 'middleman-minify-html'

gem "middleman-imageoptim", :git => "https://github.com/plasticine/middleman-imageoptim", :branch => "master"
